title: Vova Puchkov awesome blog
author: tellmywife
email: vova.puchkoff@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Vova Puchkov personal blog

# social links
github_username:  tellmywife # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
